# Generated by Django 5.2.3 on 2025-07-11 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('skills_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('experience_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('education_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('formatting_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('extracted_skills', models.JSONField(blank=True, default=list)),
                ('skill_gaps', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('industry_keywords', models.JSONField(blank=True, default=list)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('analysis_version', models.CharField(default='1.0', max_length=20)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resumes.resume')),
            ],
        ),
        migrations.CreateModel(
            name='CareerInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('skill_gap', 'Skill Gap'), ('career_path', 'Career Path'), ('market_trend', 'Market Trend'), ('improvement', 'Improvement Suggestion')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], max_length=20)),
                ('action_items', models.JSONField(blank=True, default=list)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_insights', to='analyzer.resumeanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='SkillAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('relevance_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('industry_demand', models.CharField(choices=[('high', 'High Demand'), ('medium', 'Medium Demand'), ('low', 'Low Demand')], max_length=20)),
                ('skill_category', models.CharField(choices=[('technical', 'Technical Skills'), ('soft', 'Soft Skills'), ('language', 'Programming Languages'), ('tools', 'Tools & Technologies'), ('certification', 'Certifications')], max_length=50)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_analyses', to='analyzer.resumeanalysis')),
            ],
        ),
    ]
